### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by solonjhee** [jsb/PicoPoisons#2]
Just installed the addon and this is what I see in the upper right corner by my weapon buffs:

https://imgur.com/a/tph1tKD

Shows "lol" instead of number of charges.  I couldn't find any kind of a menu or options.  Not sure what is wrong.

**Comment by jsb** [comment]
That sounds like an outdated version. There are currently no official releases for Classic, but can you try downloading the [latest master version](https://github.com/jsb/PicoPoisons/archive/master.zip)?

**Comment by solonjhee** [comment]
Interesting that there is no official release for classic because this website says it's an official release for classic (https://github.com/jsb/PicoPoisons).

I think the problem was for some reason the link I downloaded from before had no ".gitignore" file.  So I redownloaded your master link and then deleted everything and re-added everything to Addons and now it's working.

Thanks again!

**Comment by jsb** [comment]
I was trying to say I've not released this AddOn on any of the usual repositories yet (CurseForge, WoWInterface, etc.), and there is no current Classic release on the [Releases](https://github.com/jsb/PicoPoisons/releases) tab of this project.

I'll be doing some more internal testing of this AddOn and then I might release it at some point.
